services:

  produtosapp:
    container_name: produtosapp_api
    build:
       context: .
       dockerfile: ProdutosApp.API/Dockerfile
    ports:
       - "8081:8080"
    networks:
      - coti_network
    depends_on:
       - sqlserver_produtosapp

  sqlserver_produtosapp:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Coti@2025
    restart: unless-stopped
    networks:
      - coti_network
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

networks:
  coti_network:
    driver: bridge